### PR TITLE
[Beta] New features

### PR DESCRIPTION
**Pull request by Sid72020123**
## NOTE:

It is taking a lot of time for me to implement new features because of my school. I will try to continue making the new features when I get time.

**Some features are still experimental and may still not work! Please use the stable version instead!**

**This code is not going to be merged and uploaded to pypi.org until I update and make this stable.**

**This code is not uploaded on pypi.org yet...**

I kept the code here as a backup.
To use, download the code.

## Many features are still experimental and might break/won't work!
Try login in with replit and other online IDEs:
```py
import scratchconnect

cookie = {
    "Username": "<your username>",
    "SessionID": "<your session id>"
}

login = scratchconnect.ScratchConnect(online_ide_cookie=cookie)
```

For Cloud Requests, arguments still don't work. Sorry, I don't have enough time to document it here.
Cloud Requests Scratch Project can be found on Project ID: 720252660 (Unshared)

I'm very sorry. I am busy because of my school and get very less time to work on this project. Development s very slow and may  take much time to complete.

### CODE REVIEW

**Comment by UniqueName12345** [comment]
> This pull request **introduces 3 alerts** when merging [22c7795](https://github.com/Sid72020123/scratchconnect/commit/22c7795795850638dadfb365c3372384d4d984ff) into [b312d55](https://github.com/Sid72020123/scratchconnect/commit/b312d55764553826d778866f4c1ed7ef0cff33cb) - [view on LGTM.com](https://lgtm.com/projects/g/Sid72020123/scratchconnect/rev/pr-2b477de6e4da3700a39bc29689e8fd70fa61e09d)
> 
> **new alerts:**
> 
>     * 3 for Except block handles 'BaseException'

Uhhh... @Sid72020123, you may want to deal with that before uploading onto pypi. 😛

**Comment by Sid72020123** [comment]
> > This pull request **introduces 3 alerts** when merging [22c7795](https://github.com/Sid72020123/scratchconnect/commit/22c7795795850638dadfb365c3372384d4d984ff) into [b312d55](https://github.com/Sid72020123/scratchconnect/commit/b312d55764553826d778866f4c1ed7ef0cff33cb) - [view on LGTM.com](https://lgtm.com/projects/g/Sid72020123/scratchconnect/rev/pr-2b477de6e4da3700a39bc29689e8fd70fa61e09d)
> > **new alerts:**
> > ```
> > * 3 for Except block handles 'BaseException'
> > ```
> 
> Uhhh... @Sid72020123, you may want to deal with that before uploading onto pypi. 😛

Yes! Actually I am not going to upload it now...
I created a pull request just for backup.

**Comment by Sid72020123** [comment]
> Cool! Finally i can use Replit with ScratchConnect _Beta_, yet _**:)**_ Thank you @Sid72020123, also i now need to make an part 2 of the book 😭

You're welcome! But the features are still experimental and the proxy will work only till 28 Nov... I can create a new proxy.
I added only the GET requests to keep your data safe.

I can't help you to make a new book. Sorry.

**Comment by WojtekCodesToday** [comment]
Just add the instructions

niedz., 9 paź 2022, 06:17 użytkownik Siddhesh Chavan <
***@***.***> napisał:

**Pull request closed without merging**
