### PR TITLE
Add Aviate Status

### PR DESCRIPTION
**Pull request by Mbrick2**
[Aviate](aviate.vercel.app) is rising in popularity and Scratch Connect should join in

### CODE REVIEW

**Comment by Sid72020123** [comment]
I will add this later...
I am really very sorry but I'm little busy now :(
I will make sure to merge this with the next release...

**Comment by Sid72020123** [comment]
But don't you think, the function name should be "aviate_data"?

**Comment by Mbrick2** [comment]
> But don't you think, the function name should be "aviate_data"?

Ahh yes. [6e7c6f7](https://github.com/Sid72020123/scratchconnect/pull/37/commits/6e7c6f707648eb686b6360a0bcc7cc7e1be9a547)

**Comment by aidaner** [comment]
lol

**Comment by Sid72020123** [comment]
Good. This will soon be merged with the next update...

**Pull request merged**
